
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Subhakshi Sharma
 */
public class AddCourse extends javax.swing.JFrame {
  Connection con=null;
  Statement pst=null;
  ResultSet rs=null;
  public void selectionall() throws SQLException{
    try {
        con= DriverManager.getConnection("jdbc:derby://localhost:1527/coaching","sakshi","2896");       
             pst = con.createStatement();
             rs=pst.executeQuery("select * from SAKSHI.COURSE");
             coursetable.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (SQLException ex) {
        ex.printStackTrace();    }
}

    /**
     * Creates new form AddCourse
     */
    public AddCourse() throws SQLException {
        initComponents();
        selectionall();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        courseid = new javax.swing.JTextField();
        lbl_courseid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        coursename = new javax.swing.JTextField();
        lbl_coursename = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        coursefees = new javax.swing.JTextField();
        lbl_coursefees = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        courseduration = new javax.swing.JTextField();
        lbl_courseduration = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursetable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ADD COURSE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 587, 25));

        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 1, -1, -1));

        jLabel2.setText("COURSE ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 97, 30));

        courseid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                courseidKeyReleased(evt);
            }
        });
        getContentPane().add(courseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 55, 152, 30));
        getContentPane().add(lbl_courseid, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 55, 190, 20));

        jLabel3.setText("COURSE NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, 97, 30));

        coursename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coursenameKeyReleased(evt);
            }
        });
        getContentPane().add(coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 105, 152, 30));
        getContentPane().add(lbl_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 115, 190, 20));

        jLabel4.setText("COURSE FEES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 97, 30));

        coursefees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coursefeesKeyReleased(evt);
            }
        });
        getContentPane().add(coursefees, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 164, 152, 30));
        getContentPane().add(lbl_coursefees, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 174, 190, 20));

        jLabel5.setText("COURSE DURATION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, -1, 30));

        courseduration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coursedurationKeyReleased(evt);
            }
        });
        getContentPane().add(courseduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 214, 152, 30));
        getContentPane().add(lbl_courseduration, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 224, 190, 20));

        save.setBackground(new java.awt.Color(102, 104, 0));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 299, -1, -1));

        reset.setBackground(new java.awt.Color(255, 102, 102));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 299, -1, -1));

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 299, -1, -1));

        coursetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "COURSEID", "COURSENAME", "FEES", "DURATION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(coursetable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 370, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        HomePage hp=new HomePage();
        hp.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void courseidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseidKeyReleased
        lbl_courseid.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_courseidKeyReleased

    private void coursenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursenameKeyReleased
        lbl_coursename.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_coursenameKeyReleased

    private void coursefeesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursefeesKeyReleased
        lbl_coursefees.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_coursefeesKeyReleased

    private void coursedurationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursedurationKeyReleased
        lbl_courseduration.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_coursedurationKeyReleased

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       try {
             con= DriverManager.getConnection("jdbc:derby://localhost:1527/coaching","sakshi","2896");     
                String query="insert into SAKSHI.COURSE values(?,?,?,?)";
             PreparedStatement ps=con.prepareStatement(query);
ps.setString(1,courseid.getText());
ps.setString(2,coursename.getText());
ps.setString(3,coursefees.getText());
ps.setString(4,courseduration.getText());
int status=ps.executeUpdate();
if(status==1)
{
JOptionPane.showMessageDialog(null, "inserted successfully");
ps.close();
}
else
{
System.out.println("Inserting failed");
ps.close();
}    
             pst = con.createStatement();
             rs=pst.executeQuery("select * from SAKSHI.COURSE");
             coursetable.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (SQLException ex) {
       System.out.println("Exception occur in Add Button "+ex);
          }        
        String CID=courseid.getText();
        if(courseid.getText().trim().isEmpty())
        {
            lbl_courseid.setText("course id is mandatory");
        }
        String CN=coursename.getText();
        if(coursename.getText().trim().isEmpty())
        {
            lbl_coursename.setText("course name is mandatory");
        }
        if(coursefees.getText().trim().isEmpty())
        {
            lbl_coursefees.setText("fees is mandatory");
        }
        if(courseduration.getText().trim().isEmpty())
        {
            lbl_courseduration.setText("student id is mandatory");
        }
            // TODO add your handling code here
        
                
    }//GEN-LAST:event_saveActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        courseid.setText(null);
        coursename.setText(null);
        coursefees.setText(null);
          courseduration.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        AdminPage ap=new AdminPage();
        ap.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddCourse().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddCourse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField courseduration;
    private javax.swing.JTextField coursefees;
    private javax.swing.JTextField courseid;
    private javax.swing.JTextField coursename;
    private javax.swing.JTable coursetable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_courseduration;
    private javax.swing.JLabel lbl_coursefees;
    private javax.swing.JLabel lbl_courseid;
    private javax.swing.JLabel lbl_coursename;
    private javax.swing.JButton logout;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
