
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Subhakshi Sharma
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        addteacher = new javax.swing.JButton();
        addstudent = new javax.swing.JButton();
        addcourse = new javax.swing.JButton();
        viewteacher = new javax.swing.JButton();
        viewstudent = new javax.swing.JButton();
        viewcourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("  ADMIN PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 480, 30));

        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 11, -1, 30));

        addteacher.setText("ADD TEACHER");
        addteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addteacherActionPerformed(evt);
            }
        });
        getContentPane().add(addteacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 111, 125, 36));

        addstudent.setText("ADD STUDENT");
        addstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentActionPerformed(evt);
            }
        });
        getContentPane().add(addstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 111, 125, 36));

        addcourse.setText("ADD COURSE");
        addcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcourseActionPerformed(evt);
            }
        });
        getContentPane().add(addcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 111, 128, 36));

        viewteacher.setText("VIEW TEACHER");
        viewteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewteacherActionPerformed(evt);
            }
        });
        getContentPane().add(viewteacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 167, 125, 36));

        viewstudent.setText("VIEW STUDENT");
        viewstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstudentActionPerformed(evt);
            }
        });
        getContentPane().add(viewstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 167, 125, 36));

        viewcourse.setText("VIEW COURSE");
        viewcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcourseActionPerformed(evt);
            }
        });
        getContentPane().add(viewcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 167, 128, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        HomePage hp=new HomePage();
        hp.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void addteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addteacherActionPerformed
        AddTeacher at = null;
        try {
            at = new AddTeacher();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        at.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_addteacherActionPerformed

    private void addstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentActionPerformed
        AddStudent as = null;
        try {
            as = new AddStudent();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        as.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_addstudentActionPerformed

    private void addcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcourseActionPerformed
        AddCourse ac = null;
        try {
            ac = new AddCourse();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        ac.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_addcourseActionPerformed

    private void viewteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewteacherActionPerformed
        ViewTeacher vc = null;
        try {
            vc = new ViewTeacher();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        vc.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewteacherActionPerformed

    private void viewstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstudentActionPerformed
        ViewStudent vs = null;
        try {
            vs = new ViewStudent();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        vs.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewstudentActionPerformed

    private void viewcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcourseActionPerformed
        ViewCourse vc = null;
        try {
            vc = new ViewCourse();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        vc.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewcourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcourse;
    private javax.swing.JButton addstudent;
    private javax.swing.JButton addteacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton viewcourse;
    private javax.swing.JButton viewstudent;
    private javax.swing.JButton viewteacher;
    // End of variables declaration//GEN-END:variables
}
