
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Subhakshi Sharma
 */
public class TeacherLogin extends javax.swing.JFrame {
Connection con=null;
  Statement pst=null;
  ResultSet rs=null;
  public void selectionall() throws SQLException{
    try {

             con= DriverManager.getConnection("jdbc:derby://localhost:1527/coaching","sakshi","2896");       
             pst = con.createStatement();
             rs=pst.executeQuery("select * from SAKSHI.TEACHERPASSWORD");           
  } catch (SQLException ex) {
        ex.printStackTrace();    
   } }
    /**
     * Creates new form TeacherLogin
     */
    public TeacherLogin() throws Exception{
        initComponents();
        selectionall();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        teacher = new javax.swing.JButton();
        student = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        teacherid = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        newregister = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        coaching = new javax.swing.JButton();
        lbl_teacherid = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(153, 153, 255));
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 85, 31));

        admin.setBackground(new java.awt.Color(153, 153, 255));
        admin.setText("ADMIN");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        getContentPane().add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 11, 82, 33));

        teacher.setBackground(new java.awt.Color(153, 153, 255));
        teacher.setText("TEACHER");
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });
        getContentPane().add(teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 11, 88, 33));

        student.setBackground(new java.awt.Color(153, 153, 255));
        student.setText("STUDENT");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        getContentPane().add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 11, 88, 33));

        jLabel1.setText(" TEACHER LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 813, 25));

        jLabel2.setText("TEACHER ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, 85, 30));

        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, 85, 30));

        teacherid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacheridActionPerformed(evt);
            }
        });
        teacherid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                teacheridKeyReleased(evt);
            }
        });
        getContentPane().add(teacherid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 137, 107, 30));

        login.setBackground(new java.awt.Color(102, 255, 0));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 312, -1, 35));

        reset.setBackground(new java.awt.Color(255, 102, 102));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 312, -1, 35));

        newregister.setBackground(new java.awt.Color(102, 102, 255));
        newregister.setText("NEW REGISTER");
        newregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newregisterActionPerformed(evt);
            }
        });
        getContentPane().add(newregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 374, 131, 35));

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 197, 107, 30));

        coaching.setBackground(new java.awt.Color(153, 153, 255));
        coaching.setText("COACHING");
        coaching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachingActionPerformed(evt);
            }
        });
        getContentPane().add(coaching, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 11, 100, 33));
        getContentPane().add(lbl_teacherid, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 137, 175, 30));
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 197, 175, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
HomePage hp=new HomePage();
hp.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
TeacherLogin tl = null;
    try {
        tl = new TeacherLogin();
    } catch (Exception ex) {
        Logger.getLogger(TeacherLogin.class.getName()).log(Level.SEVERE, null, ex);
    }
tl.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
StudentLogin sl=new StudentLogin();
sl.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_studentActionPerformed

    private void teacheridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacheridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacheridActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
     String TID=teacherid.getText();
     String PASS=password.getText();
        try{
      int log=1;
      con= DriverManager.getConnection("jdbc:derby://localhost:1527/coaching","sakshi","2896");
      pst=(Statement)con.createStatement();
      rs=pst.executeQuery("select PASSWORD from TEACHERPASSWORD where TEACHERID='"+teacherid.getText()+"'");
     rs.next();
     String tempPass=rs.getString(1);   
     if(tempPass.equals(password.getText()))
    { 
        JOptionPane.showMessageDialog(null,"successful");
        TeacherPage tp=new TeacherPage();
        tp.setVisible(true);
        this.setVisible(false);
    }
    else{
        JOptionPane.showMessageDialog(null,"Incorrect Password");
    }
  } catch (SQLException ex) {
      JOptionPane.showMessageDialog(null,"User Not Found");
      
        //Logger.getLogger(TeacherLogin.class.getName()).log(Level.SEVERE, null, ex);
    }
       /* private void CloseMe()
        {
            WindowEvent meClose=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(meClose);
        }*/
        //  try {

            // con= DriverManager.getConnection("jdbc:derby://localhost:1527/coaching","sakshi","2896");       
            /* pst = con.createStatement();
             rs=pst.executeQuery("insert into SAKSHI.COURSE values("+courseid.getText()+","+coursename.getText()+","+coursefees.getText()+","+courseduration.getText());
             // rs=st.executeQuery("select * from java.Vcustomer");  */
 
             //String query="insert into SAKSHI.TEACHERPASSWORD values(?,?,?)";
            /* String query="select * from SAKSHI.TEACHERPASSWORD where teacherid=? and password=?)";
             PreparedStatement ps=con.prepareStatement(query);
ps.setString(1,teacherid.getText());
ps.setString(2,password.getText());
//ps.setString(3,confirm.getText());
//ps.setString(4,courseduration.getText());

int status=ps.executeUpdate();
if(status==1)
{
JOptionPane.showMessageDialog(null,"matched");
ps.close();
}
else
{
JOptionPane.showMessageDialog(null,"not matched");
ps.close();
}

//con= DriverManager.getConnection("jdbc:derby://localhost:1527/coaching","sakshi","2896");       
             pst = con.createStatement();
             //rs=pst.executeQuery("select * from SAKSHI.TEACHERPASSWORD");
             // rs=st.executeQuery("select * from java.Vcustomer");
 //coursetable.setModel(DbUtils.resultSetToTableModel(rs));
 
 


    } catch (SQLException ex) {
       System.out.println("Exception occur in Add Button "+ex);
        //ex.printStackTrace();    
    }
        if(teacherid.getText().trim().isEmpty())
     {
      lbl_teacherid.setText("teacher id is mandatory");   
         }
         if(password.getText().trim().isEmpty())
     {
      lbl_password.setText("password is mandatory");   
         }
         else
         {
        TeacherPage s=new TeacherPage();
         s.setVisible(true);
         }*/// TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void newregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newregisterActionPerformed
      TeacherRegistration s = null;
    try {
        s = new TeacherRegistration();
    } catch (Exception ex) {
        Logger.getLogger(TeacherLogin.class.getName()).log(Level.SEVERE, null, ex);
    }
       s.setVisible(true);
       this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_newregisterActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
AdminLogin al=new AdminLogin();
al.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
     teacherid.setText(null);
     password.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void coachingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachingActionPerformed
      Coaching c=new Coaching();
      c.setVisible(true);
      this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_coachingActionPerformed

    private void teacheridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teacheridKeyReleased
       lbl_teacherid.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_teacheridKeyReleased

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
       lbl_password.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TeacherLogin().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TeacherLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton coaching;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_teacherid;
    private javax.swing.JButton login;
    private javax.swing.JButton newregister;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    private javax.swing.JButton student;
    private javax.swing.JButton teacher;
    private javax.swing.JTextField teacherid;
    // End of variables declaration//GEN-END:variables
}
